name: my-site
version: 0.1.0.0
synopsis: poberezkin.com website
github: epoberezkin/poberezkin.com
homepage: https://github.com/epoberezkin/poberezkin.com
license: MIT
author: Evgeny Poberezkin
copyright: 2016-2020 Evgeny Poberezkin
category: Web
extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5

executables:
  my-site:
    source-dirs: src
    main: Main.hs
    ghc-options: -threaded
    dependencies:
      - hakyll == 4.13.*
      - split == 0.2.*
      - uri-encode == 1.5.*

  users-api:
    source-dirs: posts
    main: 2020-03-15-haskell-a-higher-order-language.lhs
    ghc-options: -pgmL markdown-unlit
    dependencies:
      - markdown-unlit == 0.5.*
      - aeson == 1.4.*
      - containers == 0.6.*
      - servant >= 0.16 && < 0.18
      - servant-server >= 0.16 && < 0.18
      - warp == 3.3.*

  elevator:
    source-dirs: posts
    main: 2020-06-29-modeling-state-machine-dependent-types-haskell-1.lhs
    ghc-options: -pgmL markdown-unlit
    dependencies:
      - markdown-unlit == 0.5.*
      - interact == 0.2.*
      - singletons == 2.6.*

  atm:
    source-dirs: posts
    main: 2020-09-04-dependent-types-to-code-are-what-static-types-to-data.lhs
    ghc-options: -pgmL markdown-unlit
    dependencies:
      - markdown-unlit == 0.5.*
      - freer-indexed == 0.1.*
      - singletons == 2.6.*

ghc-options:
  - -Wall
  - -Wcompat
  - -Worphans
  - -Werror=incomplete-patterns
  - -Wredundant-constraints
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
